WIP:  Enable using host networking for Controller Plugin pods.
ceph/ceph-csi-operator pull request #176
Opened 2024-11-15 19:15 UTC by obnoxxx

# Describe what this PR does #

This work in progress is a draft PR for the implementation of host Networking for controller plugin pods  as described in https://github.com/ceph/ceph-csi-operator/blob/main/docs/design/hostNetwork.md

## Is there anything that requires special attention ##

This a first draft and  still  needs to be thoroughly tested.

Is the change backward compatible?

should be but needs testing.

Are there concerns around backward compatibility?

see issue #157  for background and context.

This PR is currently based on PR #175  to let it pass unit tests.

It will need to be rebased should that other PR merge. 

## Related issues ##

Fixes: #157 

## Future concerns ##

none.

**Checklist:**

* [ ] **Commit Message Formatting**: Commit titles and messages follow
  guidelines in the [developer
  guide](https://github.com/ceph/ceph-csi-operator/blob/main/docs/development-guide.md#commit-messages).
* [ ] Reviewed the developer guide on [Submitting a Pull
  Request](https://github.com/ceph/ceph-csi-operator/blob/main/docs/development-guide.md#development-workflow)
* [ ] [Pending release
  notes](https://github.com/ceph/ceph-csi-operator/blob/main/PendingReleaseNotes.md)
  updated with breaking and/or notable changes for the next major release.
* [ ] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

2024-11-15 19:17 UTC, obnoxxx commented
@nb-ohad , @Madhu-1 , @leelavg , @rohan47, FYI:

2024-11-19 08:33 UTC, Madhu-1 requested changes
@obnoxxx please test both cephfs/rbd with below combination
* cephfs and RBD Driver running on Host network
* cephfs and RBD Driver running on pod network
* cephfs and RBD Driver with csiaddons running on Host hetwork
* cephfs and RBD Driver with csiaddons running on pod network

I expect some port conflict as csiaddons uses same port for cephfs and rbd deployments https://github.com/ceph/ceph-csi-operator/blob/62dc94e55c32c0edd97c66fb35a62adf2549731e/internal/controller/driver_controller.go#L774

2024-11-19 08:33 UTC, Madhu-1 commented on api/v1alpha1/driver_types.go
> +
Please remove this empty line

2024-11-21 09:15 UTC, obnoxxx commented on api/v1alpha1/driver_types.go
> +
done

2024-11-21 09:18 UTC, Madhu-1 commented on internal/controller/driver_controller.go
> +
please remove this new line as well.

2024-11-21 09:19 UTC, Madhu-1 commented
@obnoxxx there is a typo in commit message as well PTAL.

2024-11-25 11:53 UTC, obnoxxx commented
@Madhu-1  wrote:
> @obnoxxx there is a typo in commit message as well PTAL.

Thanks for pointing out! fixed.

2025-01-08 20:06 UTC, closed without merging

2025-01-13 15:48 UTC, rohan47 commented
I am testing the changes of this PR

2025-01-13 17:58 UTC, obnoxxx commented
/reopen

2025-01-13 18:28 UTC, nb-ohad commented
/reopen